export type {
  SessionProtocolDelta,
  SessionProtocolPendingUserMessage,
  SessionProtocolPendingUserMessagesMessage,
  SessionProtocolPendingUserMessagesState,
  SessionProtocolSnapshot,
} from "../protocol/index.js";
export { applySessionProtocolDelta } from "../protocol/index.js";
export type {
  SessionProtocolDeltaListener,
  SessionProtocolEphemeralListener,
  SessionProtocolFailureListener,
  SessionProtocolPendingUserMessagesListener,
  SessionProtocolSpawnedProcess,
  SessionProtocolTransport,
  TauSessionProtocolError,
  TauSessionProtocolErrorCode,
  WebSocketSessionProtocolTransportOptions,
} from "../transport/index.js";
export {
  StdioSessionProtocolTransport,
  TauProcessError,
  TauSessionClientError,
  TauSessionProtocolResponseError,
  TauTransportError,
  WebSocketSessionProtocolTransport,
} from "../transport/index.js";
export { createTauSdkClient, createTauSdkWebSocketClient } from "./client.js";
export { createTauSdkClientFromTransport } from "./session.js";
export { getTauSdkSessionTurnOutcome } from "./turn_outcome.js";
export type {
  TauSdkAutocompletePathsResult,
  TauSdkClient,
  TauSdkClientOptions,
  TauSdkCreateSessionInput,
  TauSdkDelta,
  TauSdkDeltaListener,
  TauSdkEphemeral,
  TauSdkEphemeralAgentTool,
  TauSdkEphemeralCloseResult,
  TauSdkEphemeralCreateResult,
  TauSdkEphemeralListener,
  TauSdkEphemeralSubmitResult,
  TauSdkInitializeParams,
  TauSdkPendingUserMessagesListener,
  TauSdkPendingUserMessagesMessage,
  TauSdkPendingUserMessagesState,
  TauSdkReadyMessage,
  TauSdkRequestId,
  TauSdkResolvePromptResult,
  TauSdkSession,
  TauSdkSessionCancelPendingMessagesResult,
  TauSdkSessionClearGoalResult,
  TauSdkSessionClient,
  TauSdkSessionCompactResult,
  TauSdkSessionExecResult,
  TauSdkSessionInterruptResult,
  TauSdkSessionInterruptSubagentResult,
  TauSdkSessionProtocolMethod,
  TauSdkSessionQueueResult,
  TauSdkSessionRecordResult,
  TauSdkSessionReloadResult,
  TauSdkSessionResumeGoalResult,
  TauSdkSessionRetryResult,
  TauSdkSessionRewindResult,
  TauSdkSessionSampleInput,
  TauSdkSessionSampleResult,
  TauSdkSessionSetPersonaResult,
  TauSdkSessionSetReasoningResult,
  TauSdkSessionSnapshotResult,
  TauSdkSessionStartGoalResult,
  TauSdkSessionSteerResult,
  TauSdkSessionSubmitResult,
  TauSdkSessionSummary,
  TauSdkSessionTurnOutcome,
  TauSdkSessionUnobserveResult,
  TauSdkSessionUserMessageOptions,
  TauSdkTransportClientOptions,
  TauSdkWebSocketClientOptions,
} from "./types.js";
export type { TauSdkUserTextProjection } from "./user_text.js";
export { getTauUserDisplayText, getTauUserModelText, projectTauUserText } from "./user_text.js";
