import type { ThemeDefinition } from "./content_loader.js";

export const PALETTE_TOKEN_NAMES = [
  "brandAccent",
  "textMuted",
  "textDim",
  "linkText",
  "thinkingText",
  "codeInlineText",
  "codeBlockText",
  "editorBorder",
  "editorSubagentBorder",
  "editorBorderBash",
  "editorBorderRecording",
  "editorPlaceholder",
  "autocompleteSelectedSurface",
  "autocompleteSelectedText",
  "feedback",
  "feedbackError",
  "actionRunning",
  "actionSuccess",
  "actionError",
  "actionOutput",
  "diffAdd",
  "diffRemove",
  "userSurface",
  "userText",
  "userReviewSurface",
  "userReviewText",
  "userReviewTextMuted",
  "userReviewTextDim",
] as const;

export const builtinThemes: ThemeDefinition[] = [
  {
    id: "crimson",
    tokens: {
      brandAccent: "#d9a8b6",
      textMuted: "#a29d9e",
      textDim: "#767474",
      linkText: "#d9a8b6",
      thinkingText: "#767474",
      codeInlineText: "#d9a8b6",
      codeBlockText: "#d9a8b6",
      editorBorder: "#ab9399",
      editorSubagentBorder: "#ab9399",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#767474",
      autocompleteSelectedSurface: "#292526",
      autocompleteSelectedText: "#e7e3e4",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#767474",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#292526",
      userText: "#e7e3e4",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#a54d6c",
        textMuted: "#8d8386",
        textDim: "#b5afb1",
        linkText: "#a54d6c",
        thinkingText: "#b5afb1",
        codeInlineText: "#a54d6c",
        codeBlockText: "#a54d6c",
        editorBorder: "#784e5b",
        editorSubagentBorder: "#784e5b",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#b5afb1",
        autocompleteSelectedSurface: "#faf8f8",
        autocompleteSelectedText: "#100c0d",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#b5afb1",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#faf8f8",
        userText: "#100c0d",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/crimson.json",
    scope: "builtin",
  },
  {
    id: "ember",
    tokens: {
      brandAccent: "#dba9a5",
      textMuted: "#a29d9c",
      textDim: "#767473",
      linkText: "#dba9a5",
      thinkingText: "#767473",
      codeInlineText: "#dba9a5",
      codeBlockText: "#dba9a5",
      editorBorder: "#ac9391",
      editorSubagentBorder: "#ac9391",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#767473",
      autocompleteSelectedSurface: "#292525",
      autocompleteSelectedText: "#e7e4e3",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#767473",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#292525",
      userText: "#e7e4e3",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#a94f4b",
        textMuted: "#8d8383",
        textDim: "#b5b0af",
        linkText: "#a94f4b",
        thinkingText: "#b5b0af",
        codeInlineText: "#a94f4b",
        codeBlockText: "#a94f4b",
        editorBorder: "#7b4f4c",
        editorSubagentBorder: "#7b4f4c",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#b5b0af",
        autocompleteSelectedSurface: "#faf8f7",
        autocompleteSelectedText: "#100c0c",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#b5b0af",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#faf8f7",
        userText: "#100c0c",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/ember.json",
    scope: "builtin",
  },
  {
    id: "gold",
    tokens: {
      brandAccent: "#d8ad97",
      textMuted: "#a29d9b",
      textDim: "#767473",
      linkText: "#d8ad97",
      thinkingText: "#767473",
      codeInlineText: "#d8ad97",
      codeBlockText: "#d8ad97",
      editorBorder: "#ab958b",
      editorSubagentBorder: "#ab958b",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#767473",
      autocompleteSelectedSurface: "#292624",
      autocompleteSelectedText: "#e7e4e2",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#767473",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#292624",
      userText: "#e7e4e2",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#a55628",
        textMuted: "#8d8480",
        textDim: "#b4b0ae",
        linkText: "#a55628",
        thinkingText: "#b4b0ae",
        codeInlineText: "#a55628",
        codeBlockText: "#a55628",
        editorBorder: "#78523e",
        editorSubagentBorder: "#78523e",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#b4b0ae",
        autocompleteSelectedSurface: "#faf8f7",
        autocompleteSelectedText: "#100c0b",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#b4b0ae",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#faf8f7",
        userText: "#100c0b",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/gold.json",
    scope: "builtin",
  },
  {
    id: "lime",
    tokens: {
      brandAccent: "#d0b28e",
      textMuted: "#a19e9a",
      textDim: "#757472",
      linkText: "#d0b28e",
      thinkingText: "#757472",
      codeInlineText: "#d0b28e",
      codeBlockText: "#d0b28e",
      editorBorder: "#a69886",
      editorSubagentBorder: "#a69886",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#757472",
      autocompleteSelectedSurface: "#282623",
      autocompleteSelectedText: "#e6e4e2",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#757472",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#282623",
      userText: "#e6e4e2",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#996100",
        textMuted: "#8b857e",
        textDim: "#b3b0ad",
        linkText: "#996100",
        thinkingText: "#b3b0ad",
        codeInlineText: "#996100",
        codeBlockText: "#996100",
        editorBorder: "#715735",
        editorSubagentBorder: "#715735",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#b3b0ad",
        autocompleteSelectedSurface: "#faf8f6",
        autocompleteSelectedText: "#0f0d0a",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#b3b0ad",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#faf8f6",
        userText: "#0f0d0a",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/lime.json",
    scope: "builtin",
  },
  {
    id: "grass",
    tokens: {
      brandAccent: "#c3b88c",
      textMuted: "#9f9e9a",
      textDim: "#757472",
      linkText: "#c3b88c",
      thinkingText: "#757472",
      codeInlineText: "#c3b88c",
      codeBlockText: "#c3b88c",
      editorBorder: "#9f9b86",
      editorSubagentBorder: "#9f9b86",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#757472",
      autocompleteSelectedSurface: "#272623",
      autocompleteSelectedText: "#e5e4e2",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#757472",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#272623",
      userText: "#e5e4e2",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#836d00",
        textMuted: "#88867e",
        textDim: "#b2b1ad",
        linkText: "#836d00",
        thinkingText: "#b2b1ad",
        codeInlineText: "#836d00",
        codeBlockText: "#836d00",
        editorBorder: "#665c34",
        editorSubagentBorder: "#665c34",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#b2b1ad",
        autocompleteSelectedSurface: "#f9f8f6",
        autocompleteSelectedText: "#0e0d0a",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#b2b1ad",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#f9f8f6",
        userText: "#0e0d0a",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/grass.json",
    scope: "builtin",
  },
  {
    id: "emerald",
    tokens: {
      brandAccent: "#b2be93",
      textMuted: "#9e9f9b",
      textDim: "#747573",
      linkText: "#b2be93",
      thinkingText: "#747573",
      codeInlineText: "#b2be93",
      codeBlockText: "#b2be93",
      editorBorder: "#989d89",
      editorSubagentBorder: "#989d89",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#747573",
      autocompleteSelectedSurface: "#262724",
      autocompleteSelectedText: "#e4e5e2",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#747573",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#262724",
      userText: "#e4e5e2",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#667815",
        textMuted: "#85877f",
        textDim: "#b0b2ad",
        linkText: "#667815",
        thinkingText: "#b0b2ad",
        codeInlineText: "#667815",
        codeBlockText: "#667815",
        editorBorder: "#58613a",
        editorSubagentBorder: "#58613a",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#b0b2ad",
        autocompleteSelectedSurface: "#f8f9f6",
        autocompleteSelectedText: "#0d0e0a",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#b0b2ad",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#f8f9f6",
        userText: "#0d0e0a",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/emerald.json",
    scope: "builtin",
  },
  {
    id: "jade",
    tokens: {
      brandAccent: "#a1c2a0",
      textMuted: "#9c9f9c",
      textDim: "#737573",
      linkText: "#a1c2a0",
      thinkingText: "#737573",
      codeInlineText: "#a1c2a0",
      codeBlockText: "#a1c2a0",
      editorBorder: "#909f8f",
      editorSubagentBorder: "#909f8f",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#737573",
      autocompleteSelectedSurface: "#252725",
      autocompleteSelectedText: "#e3e5e3",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#737573",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#252725",
      userText: "#e3e5e3",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#3d803e",
        textMuted: "#828882",
        textDim: "#afb2af",
        linkText: "#3d803e",
        thinkingText: "#afb2af",
        codeInlineText: "#3d803e",
        codeBlockText: "#3d803e",
        editorBorder: "#476547",
        editorSubagentBorder: "#476547",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#afb2af",
        autocompleteSelectedSurface: "#f7f9f7",
        autocompleteSelectedText: "#0b0e0b",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#afb2af",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#f7f9f7",
        userText: "#0b0e0b",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/jade.json",
    scope: "builtin",
  },
  {
    id: "teal",
    tokens: {
      brandAccent: "#92c4b0",
      textMuted: "#9ba09e",
      textDim: "#737574",
      linkText: "#92c4b0",
      thinkingText: "#737574",
      codeInlineText: "#92c4b0",
      codeBlockText: "#92c4b0",
      editorBorder: "#89a197",
      editorSubagentBorder: "#89a197",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#737574",
      autocompleteSelectedSurface: "#242726",
      autocompleteSelectedText: "#e2e5e4",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#737574",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#242726",
      userText: "#e2e5e4",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#008461",
        textMuted: "#808985",
        textDim: "#aeb2b0",
        linkText: "#008461",
        thinkingText: "#aeb2b0",
        codeInlineText: "#008461",
        codeBlockText: "#008461",
        editorBorder: "#386756",
        editorSubagentBorder: "#386756",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#aeb2b0",
        autocompleteSelectedSurface: "#f7f9f8",
        autocompleteSelectedText: "#0a0e0d",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#aeb2b0",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#f7f9f8",
        userText: "#0a0e0d",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/teal.json",
    scope: "builtin",
  },
  {
    id: "cyan",
    tokens: {
      brandAccent: "#8ac4c1",
      textMuted: "#9aa09f",
      textDim: "#727575",
      linkText: "#8ac4c1",
      thinkingText: "#727575",
      codeInlineText: "#8ac4c1",
      codeBlockText: "#8ac4c1",
      editorBorder: "#86a09f",
      editorSubagentBorder: "#86a09f",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#727575",
      autocompleteSelectedSurface: "#232727",
      autocompleteSelectedText: "#e2e5e5",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#727575",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#232727",
      userText: "#e2e5e5",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#00827f",
        textMuted: "#7e8988",
        textDim: "#adb2b2",
        linkText: "#00827f",
        thinkingText: "#adb2b2",
        codeInlineText: "#00827f",
        codeBlockText: "#00827f",
        editorBorder: "#2e6765",
        editorSubagentBorder: "#2e6765",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#adb2b2",
        autocompleteSelectedSurface: "#f6f9f9",
        autocompleteSelectedText: "#0a0e0e",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#adb2b2",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#f6f9f9",
        userText: "#0a0e0e",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/cyan.json",
    scope: "builtin",
  },
  {
    id: "azure",
    tokens: {
      brandAccent: "#8bc2d0",
      textMuted: "#9a9fa1",
      textDim: "#737575",
      linkText: "#8bc2d0",
      thinkingText: "#737575",
      codeInlineText: "#8bc2d0",
      codeBlockText: "#8bc2d0",
      editorBorder: "#869fa6",
      editorSubagentBorder: "#869fa6",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#737575",
      autocompleteSelectedSurface: "#232728",
      autocompleteSelectedText: "#e2e5e6",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#737575",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#232728",
      userText: "#e2e5e6",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#007d97",
        textMuted: "#7e888b",
        textDim: "#adb2b3",
        linkText: "#007d97",
        thinkingText: "#adb2b3",
        codeInlineText: "#007d97",
        codeBlockText: "#007d97",
        editorBorder: "#306572",
        editorSubagentBorder: "#306572",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#adb2b3",
        autocompleteSelectedSurface: "#f6f9fa",
        autocompleteSelectedText: "#0a0e0f",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#adb2b3",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#f6f9fa",
        userText: "#0a0e0f",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/azure.json",
    scope: "builtin",
  },
  {
    id: "cobalt",
    tokens: {
      brandAccent: "#95bdda",
      textMuted: "#9b9fa2",
      textDim: "#737576",
      linkText: "#95bdda",
      thinkingText: "#737576",
      codeInlineText: "#95bdda",
      codeBlockText: "#95bdda",
      editorBorder: "#8a9dab",
      editorSubagentBorder: "#8a9dab",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#737576",
      autocompleteSelectedSurface: "#242729",
      autocompleteSelectedText: "#e2e5e7",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#737576",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#242729",
      userText: "#e2e5e7",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#0d76ad",
        textMuted: "#80878d",
        textDim: "#aeb2b4",
        linkText: "#0d76ad",
        thinkingText: "#aeb2b4",
        codeInlineText: "#0d76ad",
        codeBlockText: "#0d76ad",
        editorBorder: "#3b617b",
        editorSubagentBorder: "#3b617b",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#aeb2b4",
        autocompleteSelectedSurface: "#f7f9fa",
        autocompleteSelectedText: "#0b0e10",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#aeb2b4",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#f7f9fa",
        userText: "#0b0e10",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/cobalt.json",
    scope: "builtin",
  },
  {
    id: "violet",
    tokens: {
      brandAccent: "#a4b8df",
      textMuted: "#9c9ea2",
      textDim: "#737476",
      linkText: "#a4b8df",
      thinkingText: "#737476",
      codeInlineText: "#a4b8df",
      codeBlockText: "#a4b8df",
      editorBorder: "#919bad",
      editorSubagentBorder: "#919bad",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#737476",
      autocompleteSelectedSurface: "#252629",
      autocompleteSelectedText: "#e3e4e7",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#737476",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#252629",
      userText: "#e3e4e7",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#4a6cb4",
        textMuted: "#82868e",
        textDim: "#afb1b5",
        linkText: "#4a6cb4",
        thinkingText: "#afb1b5",
        codeInlineText: "#4a6cb4",
        codeBlockText: "#4a6cb4",
        editorBorder: "#4b5c7f",
        editorSubagentBorder: "#4b5c7f",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#afb1b5",
        autocompleteSelectedSurface: "#f7f8fa",
        autocompleteSelectedText: "#0c0d10",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#afb1b5",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#f7f8fa",
        userText: "#0c0d10",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/violet.json",
    scope: "builtin",
  },
  {
    id: "purple",
    tokens: {
      brandAccent: "#b5b2dc",
      textMuted: "#9e9ea2",
      textDim: "#747476",
      linkText: "#b5b2dc",
      thinkingText: "#747476",
      codeInlineText: "#b5b2dc",
      codeBlockText: "#b5b2dc",
      editorBorder: "#9998ac",
      editorSubagentBorder: "#9998ac",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#747476",
      autocompleteSelectedSurface: "#262629",
      autocompleteSelectedText: "#e4e4e7",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#747476",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#262629",
      userText: "#e4e4e7",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#6c61b0",
        textMuted: "#85858d",
        textDim: "#b1b0b5",
        linkText: "#6c61b0",
        thinkingText: "#b1b0b5",
        codeInlineText: "#6c61b0",
        codeBlockText: "#6c61b0",
        editorBorder: "#5a577c",
        editorSubagentBorder: "#5a577c",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#b1b0b5",
        autocompleteSelectedSurface: "#f8f8fa",
        autocompleteSelectedText: "#0d0d10",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#b1b0b5",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#f8f8fa",
        userText: "#0d0d10",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/purple.json",
    scope: "builtin",
  },
  {
    id: "magenta",
    tokens: {
      brandAccent: "#c4add4",
      textMuted: "#a09da1",
      textDim: "#757476",
      linkText: "#c4add4",
      thinkingText: "#757476",
      codeInlineText: "#c4add4",
      codeBlockText: "#c4add4",
      editorBorder: "#a195a8",
      editorSubagentBorder: "#a195a8",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#757476",
      autocompleteSelectedSurface: "#272629",
      autocompleteSelectedText: "#e5e4e6",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#757476",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#272629",
      userText: "#e5e4e6",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#8658a1",
        textMuted: "#89848b",
        textDim: "#b2b0b4",
        linkText: "#8658a1",
        thinkingText: "#b2b0b4",
        codeInlineText: "#8658a1",
        codeBlockText: "#8658a1",
        editorBorder: "#685275",
        editorSubagentBorder: "#685275",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#b2b0b4",
        autocompleteSelectedSurface: "#f9f8fa",
        autocompleteSelectedText: "#0e0c10",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#b2b0b4",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#f9f8fa",
        userText: "#0e0c10",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/magenta.json",
    scope: "builtin",
  },
  {
    id: "rose",
    tokens: {
      brandAccent: "#d1a9c6",
      textMuted: "#a19da0",
      textDim: "#767475",
      linkText: "#d1a9c6",
      thinkingText: "#767475",
      codeInlineText: "#d1a9c6",
      codeBlockText: "#d1a9c6",
      editorBorder: "#a794a1",
      editorSubagentBorder: "#a794a1",
      editorBorderBash: "#c4b790",
      editorBorderRecording: "#d8aaae",
      editorPlaceholder: "#767475",
      autocompleteSelectedSurface: "#282527",
      autocompleteSelectedText: "#e6e4e5",
      feedback: "#cbcf9f",
      feedbackError: "#f2babf",
      actionRunning: "#f0c6bb",
      actionSuccess: "#d4d4ae",
      actionError: "#f0c4c8",
      actionOutput: "#767475",
      diffAdd: "#a7a880",
      diffRemove: "#c5979b",
      userSurface: "#282527",
      userText: "#e6e4e5",
      userReviewSurface: "#191c17",
      userReviewText: "#bfccb6",
      userReviewTextMuted: "#9fa39b",
      userReviewTextDim: "#7c7e7b",
    },
    variants: {
      light: {
        brandAccent: "#995189",
        textMuted: "#8b8389",
        textDim: "#b4b0b2",
        linkText: "#995189",
        thinkingText: "#b4b0b2",
        codeInlineText: "#995189",
        codeBlockText: "#995189",
        editorBorder: "#724f69",
        editorSubagentBorder: "#724f69",
        editorBorderBash: "#413100",
        editorBorderRecording: "#5d1124",
        editorPlaceholder: "#b4b0b2",
        autocompleteSelectedSurface: "#faf8f9",
        autocompleteSelectedText: "#0f0c0e",
        feedback: "#717500",
        feedbackError: "#ac4a5a",
        actionRunning: "#a05844",
        actionSuccess: "#757322",
        actionError: "#a0545f",
        actionOutput: "#b4b0b2",
        diffAdd: "#827f11",
        diffRemove: "#b55967",
        userSurface: "#faf8f9",
        userText: "#0f0c0e",
        userReviewSurface: "#edefec",
        userReviewText: "#1e320a",
        userReviewTextMuted: "#464d40",
        userReviewTextDim: "#696d67",
      },
    },
    sourcePath: "builtin:themes/rose.json",
    scope: "builtin",
  },
];
